### ISSUE TITLE
Add support for bought single editions

### ISSUE THREAD

**Issue by teK04** [Manko10/massengeschmack-xbmc#3]
If you buy only one edition of a magazine, it won't shown up in addon. Tested with Hoaxilla-TV.

**Comment by Manko10** [comment]
Hi, sorry for the (very) late reply. For some reason I didn't get any notification that someone wrote a bug report here. I regularly check the forum thread, but not this issue tracker.

For single episodes I'll see what I can do, but I think this has to be fixed upstream since the Kodi add-on only reads the provided feeds.

**Comment by Manko10** [comment]
Since there are no individual subscriptions or single-episode purchases anymore (and therefore also no chance of an API endpoint for single episodes), I'm closing this.
